/nxt_ros_setup:
  ros__parameters:
    devices:
      3:
        sensor_type: color
        sensor_name: color_sensor
      A:
        motor_type: other
        motor_name: sensor_motor
        motor_mimic_name: sensor
        motor_mimic_gear_ratio: -0.33333
        invert_direction: false
      B:
        motor_type: wheel_motor_l
        motor_name: wheel_motor_l
        motor_mimic_name: wheel_l
        motor_mimic_gear_ratio: -0.33333
        invert_direction: true
      C:
        motor_type: wheel_motor_r
        motor_name: wheel_motor_r
        motor_mimic_name: wheel_r
        motor_mimic_gear_ratio: -0.33333
        invert_direction: true
    robot_dimensions:
      axle_track: 0.135
      wheel_radius: 0.022
      rad_per_s_to_effort: 5.86

/joint_state_aggregator:
  ros__parameters:
    related_js_time_delta: 1000000000 # nanoseconds
